eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8901

spring:
  application:
    name: service-ribbon
  #代码调用路径追踪,连接到追踪服务器
  zipkin:
    base-url: http://localhost:8889